- Okay/Controllers/CategoryController.php
- Okay/Helpers/CatalogHelper.php
Добавлен Extender в CategoryController после определения категории
Позволяет отменить и переопределить последующее поведение контроллера при необходисти
> add Extender in CategoryController

- backend/design/html/components/compact_product_list.tpl
Устраняет баг 
В compact_product_list.tpl в одном месте name был статичным.
> Change static name of input on dynamic name

- backend/design/html/index.tpl
Добавил версию OkayCMS в title админки. В принципе и без этого версия была видна, но title как-то пусто смотрелся, по-моему.
Чуть лучше для UX
> Добавил версию OkayCMS в title админки

- Okay/Helpers/MetadataHelpers/CategoryMetadataHelper.php
- backend/design/html/seo_filter_patterns_ajax.tpl
Добавлена возможность использовать склонения второго выбранного свойства в СЕО шаблонах для страниц фильтров, по стратегии свойство+свойство
> Add second selected feature aliases to meta patterns

- backend/design/js/admintooltip/admintooltip.php
Включаем или выключаем вывод ошибок при генерации admintooltip.tpl
Даже при выключенном debug mode admintooltip.js генерируется с выводом ошибок
> Debug mode in admintooltip

- Okay/Core/Entity/order.php
При "магической" сортировке в сущности, рассматриваем переданный нам order как массив и добавляем поле сортировки на каждый элемент массива.
Сортировка сущностей сразу по нескольким полям используя стандартные методы сущности и ничего больше.
> Added sorting of entities by array of fields

- Okay/Modules/OkayCMS/Integration1C/Backend/design/html/description.tpl
Удалил лишний код из темплейта описания модуля Integration1C
Удалить лишний код
> Removing some code in Integration1C

- Okay/Core/WishList.php
- Okay/Core/config/services.php
Использование метода getList класса ProductsHelper в сервисе Wishlist вместо дублирующего этот метод кода.
Устранить дублирование кода и ипользовать единый метод для получения списка товаров.
> Using products getList in wishlist

- Okay/Core/Modules/Module.php
- Okay/Core/Modules/Modules.php
- Okay/Core/OkayContainer/OkayContainer.php
Добавляет подключение параметров из модулей.
Исправить невозможность подключать параметры из модулей.
> Including parameters from modules

- Okay/Modules/OkayCMS/AutoDeploy/Extenders/BackendExtender.php
- Okay/Modules/OkayCMS/AutoDeploy/Helpers/TranslationsHelper.php
- Okay/Modules/OkayCMS/AutoDeploy/Init/Init.php
- Okay/Modules/OkayCMS/AutoDeploy/Init/services.php
Поддержка новой сущности переводов
Поддержка новой сущности переводов
> Update for new TranslationsEntity and fix TemplateConfig usage

- Okay/Core/Console/Application.php
- Okay/Core/Console/Commands/Database/DatabaseDeployCommand.php
- Okay/Core/Console/Commands/Module/ModuleCreateCommand.php
- Okay/Core/Console/Commands/Module/ModuleCreateCommand/module/Backend/Controllers/ModuleAdmin.php.tplm
- Okay/Core/Console/Commands/Module/ModuleCreateCommand/module/Backend/design/html/module.tpl.tplm
- Okay/Core/Console/Commands/Module/ModuleCreateCommand/module/Backend/lang/en.php.tplm
- Okay/Core/Console/Commands/Module/ModuleCreateCommand/module/Backend/lang/ru.php.tplm
- Okay/Core/Console/Commands/Module/ModuleCreateCommand/module/Backend/lang/ua.php.tplm
- Okay/Core/Console/Commands/Module/ModuleCreateCommand/module/Init/Init.php.tplm
- Okay/Core/Console/Commands/Module/ModuleCreateCommand/module/Init/parameters.php.tplm
- Okay/Core/Console/Commands/Module/ModuleCreateCommand/module/Init/routes.php.tplm
- Okay/Core/Console/Commands/Module/ModuleCreateCommand/module/Init/services.php.tplm
- Okay/Core/Console/Commands/Module/ModuleCreateCommand/module/design/css.php.tplm
- Okay/Core/Console/Commands/Module/ModuleCreateCommand/module/design/js.php.tplm
Добавляет консольну комманду module:create для создания каркаса нового модуля.
Автоматизация процессов.
> Added console command create module

- backend/design/html/comments.tpl
- backend/design/html/feedbacks.tpl
- backend/design/html/order_history.tpl
Добавлено экранирование спецсимволов при выводе сообщения в истории изменения заказа, в форме ответа на комментарий и сообщение обратной связи
Предотвращение XSS.
> Escape order history message

- Okay/Modules/OkayCMS/Banners/design/html/show_banner.tpl
- design/okay_shop/css/theme.css
Добавлен кастомный класс баннеров с id группы и слайда.
Исправлено отображения svg логотипа в шапке в корзине
> added custom class for banner and fix logo svg in cart page

- backend/design/html/orders.tpl
Исправлен фильтр даты в списке заказов.
Неверно формировался временной интервал.
> Fixed date filter in the orders admin

- Okay/Modules/OkayCMS/Feeds/Backend/Core/Presets/Adapters/BackendYmlAdapter.php
Сохранение названия фида в пресете шаблоне YML
> Fixed saving the yml feed name

- Okay/Controllers/CategoryController.php
- Okay/Helpers/MetadataHelpers/CategoryMetadataHelper.php
Исправляет работу с выбранными свойствами в CategoryMetadataHelper
> Fixed selected features in categoryMetadataHelper

- backend/Controllers/OrderAdmin.php
- backend/Helpers/BackendOrdersHelper.php
- backend/Requests/BackendOrdersRequest.php
Небольшие улучшения в коде OrderAdmin и BackenOrdersHelper
Устранена ошибка при которой только что созданном товару нельзя было изменить цену и скидки считались после пересохранения. Рефакторинг кода
> Small improvements in work with purchases and discounts from OrderAdmin

- Okay/Core/Image.php
Реализует загрузку изображения с удалённого ресурса через curl. 
Получение большего контроля на процессом загрузки файла и удаление некоторого ненужного кода. В том числе: Следование редиректам вместо того, чтобы пробовать загрузить файл отдельно через http и https.
Проверка статус-кода ответа через информацию, которую отдаёт курл, вместо того, что руками получать заголовки.
Проверка длинны загруженного файла до сохранения, а не после.
> Changed the process of loading an image from a remote resource

- Okay/Modules/OkayCMS/Feeds/Core/Presets/AbstractPresetAdapter.php
Добавление метода modifyItem в AbstractPresetAdapter.
Возможность для модулей изменить товар перед тем, как он будет собран под конкретный шаблон.
> Added modifyItem method in AbstractPresetAdapter.

- Okay/Modules/OkayCMS/NovaposhtaCost/Controllers/NovaposhtaCostSearchController.php
- Okay/Modules/OkayCMS/NovaposhtaCost/Extenders/FrontExtender.php
- Okay/Modules/OkayCMS/NovaposhtaCost/Init/Init.php
- Okay/Modules/OkayCMS/NovaposhtaCost/Init/services.php
- Okay/Modules/OkayCMS/NovaposhtaCost/design/css/np.css
- Okay/Modules/OkayCMS/NovaposhtaCost/design/html/validation.js
- Okay/Modules/OkayCMS/NovaposhtaCost/design/js/np.js
- Okay/Modules/OkayCMS/NovaposhtaCost/design/lang/en.php
- Okay/Modules/OkayCMS/NovaposhtaCost/design/lang/ru.php
- Okay/Modules/OkayCMS/NovaposhtaCost/design/lang/ua.php
Добавлена Frontend и Backend валидация для полей корзины в модуле Novaposhta. Поправлен поиск городов со спец символами в названии.
> Added validation for Novaposhta in the cart

- backend/Controllers/OrderAdmin.php
Исправляет ошибку связанную с удалением скидки при пересохранении заказа.
> Fixed deleting order discounts before update in OrderAdmin

- design/okay_shop/js/okay.js
Слушатель события скрытия блока фильтров по нажатию на стрелочку теперь добавляется к документу, а не напрямую к стрелочкам.
При динамической отрисовке блока фильтров, некорректное поведение
> Changed event for fn_switch

- Okay/Modules/OkayCMS/Integration1C/Integration/Export/ExportOrders.php
Добавил фамилию в экспорт заказов в Integration1C
> Added last name into Integration1C export orders

- Okay/Modules/OkayCMS/FastOrder/design/html/fast_order_form.tpl
Добавляет данные пользователя в форму быстрого заказа
Для того, чтобы авторизованному пользователю не приходилось вводить свои данные в форму.
> Added user data to fast order form

- backend/design/js/filemanager/js/jquery.fileupload-image.js
fix upload jpg image from TinyMCE
fix uploading image. Some jpg files cannot be uploaded from TinyMCE
> fix image uploading from tinymce

- backend/design/html/email/email_order_admin.tpl
- design/okay_shop/html/email/email_order.tpl
Додав до листа адміну та користувачу інформацію про доставку.
_______________________________________________________________________________________________________________________________________
Add to mail for admin and user info about delivery.
> Add delivery to mail user/admin

- backend/ajax/search_products.php
Был доработан поиск товара для компонента compact_product_list
Теперь можно искать товары у которых в имени присутствуют символы: , . " ' (точка, запятая, одинарная и двойная кавычка)
> Fixed login ajax search in product for components compact_product_list

- Okay/Controllers/UserController.php
- Okay/Helpers/UserHelper.php
Метод необходим для внедрения в личный кабинет пользователя.
Позволяет указать при внедрении в личный кабинет пользователя при добавлении новой кастомной вкладки, что эта вкладка активна при перезагрузке страницы.
> new feature: add flag active custom tab

- Okay/Modules/OkayCMS/FastOrder/Controllers/FastOrderController.php
Локализацию комментария к быстрому заказу
Везде в контроллере перевод есть, а тут - нет. Непорядок.
> Локализация комментария к быстрому заказу

- design/okay_shop/js/okay.js
В теме `okay_shop` при автокомплите поиска "ломается" ссылка на товары:
http://dl3.joxi.net/drive/2022/09/07/0009/0563/614963/63/4c423a5916.jpg
Из-за этого не работает прямой переход на товар, а также бьются стили.
PR исправляет это.
Добавил экранирование ссылки, убрал лишнее экранирование слешей, сделал единообразные кавычки.
> formatResult fix

- design/okay_shop/html/authors.tpl
Удалены лишнее условие проверки переменой $authors в design/okay_shop/html/authors.tpl
Лишняя логика. Мелкая правка шаблона
> Fixed - removed the extra condition if in authors tpl

- Okay/Core/Cart.php
Был модифицирован класс \Okay\Core\Cart и добавлен новый функционал взаимодействия корзины с cookie
Теперь корзина хранящаяся в сессиях копируется также и в cookie на 1 месяц, т.к. максимальное время жизни сессии 1 день.
> Adding the functionality of saving the basket to cookies

- Okay/Core/BackendPostRedirectGet.php
- backend/Controllers/BlogCategoryAdmin.php
- backend/Controllers/BrandAdmin.php
- backend/Controllers/CategoryAdmin.php
- backend/Controllers/FeatureAdmin.php
- backend/Controllers/OrderAdmin.php
- backend/Controllers/PageAdmin.php
- backend/Controllers/PostAdmin.php
- backend/Controllers/ProductAdmin.php
- backend/design/html/blog_category.tpl
- backend/design/html/brand.tpl
- backend/design/html/category.tpl
- backend/design/html/feature.tpl
- backend/design/html/index.tpl
- backend/design/html/order.tpl
- backend/design/html/page.tpl
- backend/design/html/post.tpl
- backend/design/html/product.tpl
- backend/lang/en.php
- backend/lang/ru.php
- backend/lang/ua.php
Для некоторых карточек сущностей была добавлена кнопка - Применить и выйти
Более удобный пользовательский интерфейс, убрали лишнее действие, если после сохранения пользователь хочет перейти на список элементов.
> adding new button apply and quit

- design/okay_shop/html/product.tpl
Исправил синтаксис тега source в шаблоне design/okay_shop/html/product.tpl
Синтаксическая ошибка HTML
> Fixed quotes in product.tpl, strinf num 27

- Okay/Modules/OkayCMS/NovaposhtaCost/Backend/design/html/order_contact_block.tpl
- Okay/Modules/OkayCMS/NovaposhtaCost/Extenders/BackendExtender.php
- Okay/Modules/OkayCMS/NovaposhtaCost/Extenders/FrontExtender.php
- Okay/Modules/OkayCMS/NovaposhtaCost/Init/services.php
- Okay/Modules/OkayCMS/NovaposhtaCost/NovaposhtaCost.php
- Okay/Modules/OkayCMS/NovaposhtaCost/design/js/np.js
- Okay/Modules/OkayCMS/NovaposhtaCost/design/lang/en.php
- Okay/Modules/OkayCMS/NovaposhtaCost/design/lang/ru.php
- Okay/Modules/OkayCMS/NovaposhtaCost/design/lang/ua.php
Добавил для выпадающего списка параметр для selectpicker который добавляет поле поиска.
Добавлена мульти-язычность для слова -Вычисляем в файле js модуля
Добавлена значение по умолчанию при расчете объема если на задан параметр в настройках.
Добавлены в Extenders возможность подключений, вдруг необходимо другим модулям отработать другую логику, например при привязке заказа и данных отделения доставки НП.
Добавление поле для быстрого поиска отделений по части содержимого названия
Расширяет функциональность модуля.
> Added field in search select NP warehouses

- design/okay_shop/html/brands_content.tpl
Откорректирована ссылка на страницу бренда при использовании пагинации
При переключении на страницу, отличную от первой, не работтала ссылка перехода на страницу бренда
> fix brand url with pagination

- design/okay_shop/html/product.tpl
Fix shema.org brand in product
> fix shema.org brand in product

- Okay/Controllers/BrandsController.php
- Okay/Helpers/BrandsHelper.php
- design/okay_shop/html/breadcrumb.tpl
Added breadcrumbs for pagination on the brands page
Displaying breadcrumbs on pagination
> add breadcrumb to brands pages

- backend/Controllers/EmailTemplatesAdmin.php
- design/okay_shop/html/email/email_answer_to_user.tpl
Исправил ошибки в шаблоне письма ответа пользователю на комментарий.
Добавил проверку при выводе в отладочном режиме верстки письма ответа пользователю на комментарий, если метод возвращает false
Лишние данные в шаблоне.
Без проверки выдавало ошибку если метод возвращал не верстку а false.
> Fixed backend debug mode for email

- design/okay_shop/html/email/email_answer_to_user.tpl
Добавлен для примера адрес вызова отладочного режима для данного шаблона письма
> Added debug link in template

- Okay/Entities/FeaturesValuesEntity.php
- Okay/Entities/ProductsEntity.php
Были добавлены условия в некоторых точках кода на проверку наличия обязательных переменных.
Обработка ситуация при отсутствии обязательных переменных
> Fixed exception triggering on empty values

- Okay/Core/Modules/Module.php
Оталвливает состоянии ошибки при чтении и парсинге json файлы
Корректная обработка ситуация при синтаксических и других ошибках в структуре файлов module.json
> Fixed, when exception triggering on data error in module.json

- backend/design/html/product.tpl
Удаляет эффект сдвига блока после скрытия блока в админ-панели в карточке товара в блоке с картинками.
Убирает мелькание верстки при загрузки страницы админ-панели
> Fixed flickering empty block 'added new image'

- Okay/Controllers/CategoryController.php
- Okay/Helpers/FilterHelper.php
Добавление места подключения для модификаций фильтров категорий
Для более удобного подключения модулей при расширении логики фильтров
> Adding a connection location for category filter modifications

- backend/design/css/okay.css
Зелена кнопка в адмінці при наведенні курсора ставала світлішою, а інші - темнішими, це дещо спантеличує коли вони використовуються разом
> Made green button hover color change consistent with others

- design/okay_shop/css/okay.css
Були приховані коментарі jQuery Validate на сторінці оформлення замовлення
> Fixed cart error message not appearing

- backend/Helpers/BackendImportHelper.php
Изменена логика приема из csv при импорте данных url.
Изменена логика поиска или генерации нового в ситуации не нахождения значения.
Проблема возникала в ситуации когда пользователь импортировал данные на другом языке и при этом в файле не передавались данные url, в этом случае url генерировался заново.
> Changed the logic of definition and generation of url in import

- backend/design/html/order.tpl
Была добавлена ссылка в админ-панели в карточке заказа на переход на сайте на страницу товара
Улучшает UI для администратора сайта
> adding a link to the product from the order in the admin panel

- design/okay_shop/css/theme.css
Fix button buy for product card
> fix button buy for product card

- Okay/Modules/OkayCMS/NovaposhtaCost/Init/module.json
- Okay/Modules/OkayCMS/NovaposhtaCost/Init/services.php
- Okay/Modules/OkayCMS/NovaposhtaCost/NovaposhtaCost.php
- Okay/Modules/OkayCMS/NovaposhtaCost/design/lang/en.php
- Okay/Modules/OkayCMS/NovaposhtaCost/design/lang/ru.php
- Okay/Modules/OkayCMS/NovaposhtaCost/design/lang/ua.php
После выбора города появлялся select выбора отделений с не мульти-язычным текстом. Исправлено на мультиязычную переменную
Теперь в модуле NP у select выбора отделений подтягивается мульти-язычное значение из языковых файлов
> Fixed multilangual value in module NP

- design/okay_shop/css/okay.css
Fixed popup cart in mobile version
> fixed popup cart

- backend/design/css/bootstrap-select.css
- backend/design/css/okay.css
> fixed coupon in admin

- Okay/Modules/OkayCMS/FastOrder/Controllers/FastOrderController.php
При быстром заказе добавляются дополнительные данные в заказ
referer_channel и referer_source записывает в заказ
> Added method an intermediate injection site - prepareAdd

- design/okay_shop/js/okay.js
Доработка логики при определенных условиях сохранения стилей для стикера скидки после переключения варианта
После переключения терялся изначальный стиль. Мелкое визуальное несовершенство.
> Fixed in okay.js stile for discount sticker from change

- backend/design/html/order.tpl
Ссылка на проверку whois по ip заменена на другой сервис
Более удобный и информативный сервис
> Replacing the whois service in the order card

- Okay/Entities/ProductsEntity.php
Исправляет ошибку в методе removeAllResizes
Исправление синтаксической ошибки
> Mini fixed params in method implode in function removeAllResizes

- backend/index.php
Установить настройки сессии можно только до её старта или после завершения, ошибка сообщающая об этом была заглушена
> "A session is active. You cannot change the session module's ini settings at this time"

- backend/Helpers/BackendOrdersHelper.php
Скорректирован поиск правильного статуса при изменении статуса в групповых действиях над заказами при изменении статуса
Некорректно искался и определялся статус заказа в групповых действиях
> fixed change order status in orders group action

- backend/design/html/order.tpl
Изменен немного стили для мобильной версии в верстке в административной панели на странице заказа
В мобильной версии в низу страницы галочка пряталась за кнопки и footer
> Mini fix in design tpl mobile template for order.tpl

- Okay/Core/Cart.php
Добавлена логику подключения при выполнении метода при помощи ExtenderFacade
Появилась возможность подключиться с получением данных переменных метода
> Added connection logic to the method

- Okay/Modules/OkayCMS/FastOrder/Init/module.json
- Okay/Modules/OkayCMS/FastOrder/design/html/recaptcha_init_invisible.tpl
- Okay/Modules/OkayCMS/FastOrder/design/html/recaptcha_init_v2.tpl
Была немного изменена логика поиска блока при помощи javascript
Более точное нахождение блока
> Fixed find element recaptcha_fast_order on page

- design/okay_shop/css/okay.css
исправление бага всплывающего окна на мобильном
> Fix popup animated

- design/okay_shop/css/media.css
- design/okay_shop/js/okay.js
> fix mobile vh

- Okay/Modules/OkayCMS/Feeds/Backend/Controllers/FeedsAdmin.php
- Okay/Modules/OkayCMS/Feeds/Entities/FeedsEntity.php
Меняет сортировку фидов в административной панели фидов.
Не было указано сортировки по умолчанию при выводе фидов
> Fixed order sort in list feed in module Feeds

- Okay/Core/Routes/AllProductsRoute.php
- Okay/Core/Routes/RouteFactory.php
- Okay/Core/Routes/Strategies/AllProducts/DefaultStrategy.php
- backend/Helpers/BackendSettingsHelper.php
- backend/design/html/settings_router.tpl
- backend/lang/en.php
- backend/lang/ru.php
- backend/lang/ua.php
Добавляет настройку в управление ЧПУ для добавления в конец URL слеша для страницы all-products
Более полное управление формированием url на странице all-products
> Fixed slash in end url in all-products route

- Okay/Modules/OkayCMS/NovaposhtaCost/Entities/NPCitiesEntity.php
add multi language find() method for NPCitiesEntity. 
You can use autocomplete fill city in cart page in any language.
> add multi language find NP city

- Okay/Entities/UsersEntity.php
Была внесены изменения в Entity работы с пользователями.
Добавлены 2 поля по которые дополнительно будет производится поиск: last_name, phone
> Modification of user search by fields last_name and phone

- Okay/Helpers/CartHelper.php
Удаление ненужные данных
Для динамических действий в корзине некоторые лишние данные которые не требуются у способов доставки и оплаты
> Mini removing redundant data

- Okay/Core/Response.php
- Добавление type hints
- Замена громоздкой конструкции switch/case на константный ассоциативный массив кодов состояния HTTP и пояснительных фраз
- Поддержка дополнительных кодов
- Упрощение парсинга даты последнего изменения
https://github.com/OkayCMS/OkayCMS/blob/1b342b7743bfd4c92dd50e5b6972b1f862658cb2/Okay/Core/Response.php#L162-L167 https://github.com/OkayCMS/OkayCMS/blob/51ae2f570c3b61cefd7ddbac1e695bc67037c44f/Okay/Core/Response.php#L162-L165
> Core\Response formatting and extension

- 1DB_changes/update_4.3.1.sql
Удалили лишний запрос при обновлении
Нет необходимости изменять эти пользовательские данные
> Deleted custom novaposhta_key

- Okay/Core/Languages.php
- Okay/Helpers/XmlFeedHelper.php
- Okay/Modules/OkayCMS/Feeds/Core/Presets/AbstractPresetAdapter.php
- Okay/Modules/OkayCMS/Feeds/Core/Presets/Adapters/PromUaAdapter.php
- Okay/Modules/OkayCMS/Feeds/Core/Presets/Adapters/RozetkaAdapter.php
- Okay/Modules/OkayCMS/GoogleMerchant/Controllers/GoogleMerchantController.php
- Okay/Modules/OkayCMS/GoogleMerchant/Helpers/GoogleMerchantHelper.php
- Okay/Modules/OkayCMS/Hotline/Controllers/HotlineController.php
- Okay/Modules/OkayCMS/Hotline/Helpers/HotlineHelper.php
- Okay/Modules/OkayCMS/Rozetka/Controllers/RozetkaController.php
- Okay/Modules/OkayCMS/Rozetka/Helpers/RozetkaHelper.php
В фіді розетки (Модуль OkayCMS/Feeds) зроблено дублювання перекладів на українську мову характеристик та опису товара для фідів не української версії.
Привели переклади в фіді в відповідності до вимог https://sellerhelp.rozetka.com.ua/p192-automatic-translation.html
Сообщите нам, если это связано с issue(s)/PR(s) (см. https://github.blog/2013-05-14-closing-issues-via-pull-requests/)
> rozetka translate features and description

- Okay/Entities/BrandsEntity.php
- Okay/Entities/FeaturesValuesEntity.php
Була неузгодженість у фільтрації брендів/властивостей і товарів по фільтру discounted. Виправили логіку фільтра discounted, щоб вона була єдиною для товарів, брендів і властивостей
> fix discoundet filter for brand and feature

- Okay/Core/Modules/Module.php
- Okay/Core/config/services.php
- backend/index.php
Виправлена помилка, при зміні мови сайту на клієнтській частині, мультиязичні налаштування (Settings) перемикалися на нову мову після оновлення сторінки.
> fix multilang settings on change language

- Okay/Modules/OkayCMS/Banners/Backend/Controllers/BannersImageAdmin.php
- Okay/Modules/OkayCMS/Banners/Backend/design/html/banners_image.tpl
- Okay/Modules/OkayCMS/Banners/Backend/lang/en.php
- Okay/Modules/OkayCMS/Banners/Backend/lang/ge.php
- Okay/Modules/OkayCMS/Banners/Backend/lang/ru.php
- Okay/Modules/OkayCMS/Banners/Backend/lang/ua.php
- Okay/Modules/OkayCMS/Banners/DTO/SlideSettingsDTO.php
- Okay/Modules/OkayCMS/Banners/Entities/BannersImagesEntity.php
- Okay/Modules/OkayCMS/Banners/Helpers/BannersHelper.php
- Okay/Modules/OkayCMS/Banners/Helpers/BannersImagesHelper.php
- Okay/Modules/OkayCMS/Banners/Init/Init.php
- Okay/Modules/OkayCMS/Banners/Init/module.json
- Okay/Modules/OkayCMS/Banners/Requests/BannersImagesRequest.php
- Okay/Modules/OkayCMS/Banners/design/html/show_banner.tpl
Додали можливість завантажувати окреме зображення для мобільних пристроїв та керувати варіантом його відображення.
> Second banner image on mobile device

- backend/design/html/languages.tpl
- backend/lang/en.php
- backend/lang/ru.php
- backend/lang/ua.php
Исправляет ошибку формирования адреса старницы
Перенесена логика формирования url из языкового файла в файл tpl
> Fixed link to translate admin page

- backend/Controllers/ProductAdmin.php
Після внесення змін в товар і натискання "Оновити і вийти" раніше повертало просто на список товарів. Зараз повертає на список товарів + фільтр, якщо такий був вибраний
> return to filter page after update product

- backend/design/html/order_print.tpl
Додаав вивід знижок в печатну форму замовлення
> added discounts in order print

- design/okay_shop/js/okay.js
При поиске в корзине скриптами JS поля с количеством, был уточнен поиск поля по классу
При появлении нового поля ошибочное определялось скрытое поле
> Fixed find amount field for purchase in cart, added clarifying class

- Okay/Core/Cart.php
Исправляет ошибку удаления последнего товара в корзине
удаление последнего товара в корзине
> Fixed deleted last product in cart

- Okay/Controllers/CartController.php
Что PR делает?
Исправляет некритичную ошибку которая вызывает побочные трудности для работы ajax в корзине
Зачем PR нужен?
Добавлена ​​проверка на наличие значения переменной в методе carsAjaxValidate
> added check for emptiness of the array  in the cartAjaxValidate method

- Okay/Helpers/MetadataHelpers/CategoryMetadataHelper.php
Добавляет необходимые данные для замены этими данными заглушек в шаблонах у категорий в SEO фильтров
Наполняет набор в массиве данных подставляемых в шаблон
> Added data for metadata template in category

- design/okay_shop/html/register.tpl
Исправление опечатки в названии переменной
Необходимо для корректного возврата значения в поле
> Fixed request_data name value in register form

- Okay/Modules/OkayCMS/Banners/Backend/Controllers/BannersAdmin.php
Изменяет заголовки ответа при скачивании файлов бэкапа баннеров
Решает ошибку заголовков для браузера при скачивании
> Fix file download issue with backup banners in browser

- Okay/Controllers/BrandController.php
- Okay/Controllers/CategoryController.php
- Okay/Controllers/ProductsController.php
- Okay/Core/Routes/Strategies/Brand/DefaultStrategy.php
- Okay/Core/Routes/Strategies/Brand/NoPrefixStrategy.php
Изменения в роутинге отложенной загрузки фильтров для страницы бренд и фикс построения ссылки для аяксового запроса на странице поиска товаров, всех товаров, категории товара
Фикс ошибки 404 отложенной загрузки фильтров для страницы бренд и 301 редиректа на страницах отложенной загрузки фильтров поиска товаров, товаров, страниц категорий
> Fix deferred load features in brand route strategies and build  link to get ajax features data on catalog pages

- Okay/Core/Comparison.php
Не показывать выключенные в админке свойства, а так же показывать только с проставленным чекбоксом "показывать в товаре"
На странице сравнений /comparison показывались все свойства, в т.ч. и отключенные и без показа в товаре
> Fix exclude hidden features values from product comparisons

- Okay/Helpers/MetadataHelpers/CategoryMetadataHelper.php
Убирает лишний запрос в БД, небольшой рефакторинг кода
Цены в каталоге товаров уже достаются в контроллере, поэтому в CategoryMetadataHelper нет необходимости при каждом обращении к странице доставать range цен еще раз
> Removed unnecessary database query in CategoryMetadataHelper, minor refactoring

- Okay/Modules/OkayCMS/AutoDeploy/Helpers/TranslationsHelper.php
Fix мелкой ошибки в хелпере локальных переводов
На тех проектах где включен debug mode и используются локальные переводы была обнаружена ошибка обращения к несуществующему индексу
> Add check for existing translations label in addLocalTranslations method (AutoDeploy)

- Okay/Helpers/FilterHelper.php
убирает лишний запрос в БД при формировании url брендов в каталогах + мелкий фикс
> Enhance sortBrands function to handle single URL, fix ExtenderFacade

- Okay/Core/Modules/Module.php
- Okay/Core/Modules/VersionControl.php
- backend/Controllers/ModulesAdmin.php
- backend/design/html/module_list.tpl
Ошибка формирования версий на странице модулей в админке
версия 1.1.12 больше чем 1.1.2, но в в админ панели отображается сообщение что такая версия меньше текущей и не показывает кнопку обновить
> Bugfix / Added Version Comparison Module to Backend Module List Page

- design/okay_shop/html/blog_sidebar.tpl
- design/okay_shop/html/scripts.tpl
- design/okay_shop/js/okay.js
Pull request allows you to subscribe to a blog in the footer.
Pull request solve the problem with subscribing to a blog in the footer.
> fix_blog_subscribe_form

- Okay/Modules/OkayCMS/Banners/Backend/design/html/banners_image.tpl
- Okay/Modules/OkayCMS/Banners/DTO/BannerImageSettingsDTO.php
- design/okay_shop/css/okay.css
Для мобильного банерп добавлен первый активный вариант отображения по умолчанию. Поправлено отображение кнопки сохранить на странице создания слайда. Добавлен отступ для точек пагинации в клиентской части сайта
Исправление ошибки отображения слайдов
> Fix mobile banner

- 1DB_changes/update_4.5.2.sql
Меняет поля в таблице баннеров и таблице менеджеров с varchar на text для большей вместительности данных
Обновляет таблицу демо данных
> Database: change banner and manager column type to text, update demo

- 1DB_changes/update_4.5.2.sql
- backend/Helpers/BackendFeaturesValuesHelper.php
- backend/Helpers/BackendOrderHistoryHelper.php
- backend/Helpers/BackendProductsHelper.php
Изменен префикс запросов, поле categories, pages, brands сделано типом varchar
> Change database and queries with prefix

- Okay/Modules/OkayCMS/Integration1C/Integration/Import/ImportProducts.php
Была исправлена ошибка, дважды исполнялся одинаковый код по получению названия файла из URL
Корректировка кода чтобы название файла определялось корректно и файл находился и основная картинка определялась корректно.
> Fix a bug in the code for determining the name of the main image

- Okay/Core/Routes/Strategies/Category/PrefixAndPathStrategy.php
Исправляет построения пути роута PrefixAndPathStrategy категорий
> Fix Mock with slash in PrefixAndPathStrategy route

- Okay/Controllers/BlogController.php
- Okay/Core/Routes/Strategies/AllBlog/DefaultStrategy.php
Фикс изменения префикса для страницы AllBlog
> Fix AllBlog route strategy

- design/okay_shop/html/head.tpl
Исправляет атрибут type для указания favicon в шаблоне сайта
> Fix favicon MIME type based on file extension in design template

- Okay/Entities/OrdersEntity.php
Фикс массового обновления заказов случае передачи статуса paid на изменение, добавлен метод afterMarkedPaidUpdate для перехвата когда статус заказа и сам заказ полностью обновлен
> Fix markedPaid state on mass orders update and add afterMarkedPaidUpdate method

- Okay/Core/Image.php
- Okay/Core/Modules/LicenseModulesTemplates.php
- Okay/Core/Recaptcha.php
- Okay/Core/Support.php
- backend/Controllers/IndexAdmin.php
- backend/Controllers/ModulesAdmin.php
- backend/Controllers/ThemeAdmin.php
- backend/Helpers/BackendModulesHelper.php
- index.php
Уменьшает количество таймаута запросов в случае неудачного соединения или ошибки curl
> Curl request timeout and retry counter

- Okay/Core/Modules/ModuleCache.php
- Okay/Core/Modules/Modules.php
- Okay/Core/Routes/AbstractRoute.php
- Okay/Core/Routes/Strategies/BlogCategory/NoPrefixAndPathStrategy.php
- Okay/Core/Routes/Strategies/BlogCategory/PrefixAndPathStrategy.php
- Okay/Core/Routes/Strategies/Category/NoPrefixAndPathStrategy.php
- Okay/Core/Routes/Strategies/Category/PrefixAndPathStrategy.php
- Okay/Core/Routes/Strategies/Post/NoPrefixAndCategoryStrategy.php
- Okay/Core/Routes/Strategies/Post/NoPrefixAndPathStrategy.php
- Okay/Core/Routes/Strategies/Post/PrefixAndPathStrategy.php
- Okay/Core/Routes/Strategies/Product/NoPrefixAndCategoryStrategy.php
- Okay/Core/Routes/Strategies/Product/NoPrefixAndPathStrategy.php
- Okay/Core/Routes/Strategies/Product/PrefixAndPathStrategy.php
Добавляет и исправляет кеширование генерации url в разных стратегиях. Добавляет кеширование работы с модулями
Решает проблему в излишних запросах к БД на каждой странице сайта
> Cache DB queries for faster route generation and modules startup performance

- Okay/Controllers/CartController.php
- Okay/Core/config/routes.php
- design/okay_shop/html/cart.tpl
- design/okay_shop/html/cart_purchases.tpl
- design/okay_shop/js/okay.js
- design/okay_shop/lang/en.php
- design/okay_shop/lang/ru.php
- design/okay_shop/lang/ua.php
Удаляет дополнительную валидацию в корзине наличия товаров на складе из-за необходимости переосмыслить логику работы кода (неоднозначное поведение для покупателей и владельцев интернет-магазина)
> Temporary remove validation of goods for availability

- 1DB_changes/update_4.5.2.sql
- backend/Helpers/BackendFeaturesValuesHelper.php
- backend/design/html/feature.tpl
Позиция новых значений с добавлением в конец списка, поведение сортировки и добавления значений по стандартной логике Окай
> Sort new feature values by default
