- backend/design/css/okay.css
Добавил отступ у body только для `.navbar-fixed` иначе ненужный отступ и скролл в форме входа есть:
p.s. По-моему, и **в установщике отступ тоже есть ненужный.**
> Добавил отступ у body только для .navbar-fixed

- Okay/Core/Cart.php
Добавляет extension в метод updateItem класса Cart.php
Фикс бага, extension должен там быть
> Added extension in updateItem method of Cart.php

- backend/design/js/admintooltip/tooltip.tpl
Присоединяет обработчик событий в admintooltip.js не к отдельным элементам, а к элементу document
Корректная работа с динамическими элементами на странице.
> Attaching handler to the document instead of individual elements

- Okay/Helpers/MetadataHelpers/AllProductsMetadataHelper.php
- Okay/Helpers/MetadataHelpers/AuthorMetadataHelper.php
- Okay/Helpers/MetadataHelpers/BlogCategoryMetadataHelper.php
- Okay/Helpers/MetadataHelpers/BrandMetadataHelper.php
- Okay/Helpers/MetadataHelpers/CartMetadataHelper.php
- Okay/Helpers/MetadataHelpers/CategoryMetadataHelper.php
- Okay/Helpers/MetadataHelpers/CommonMetadataHelper.php
- Okay/Helpers/MetadataHelpers/MetadataInterface.php
- Okay/Helpers/MetadataHelpers/OrderMetadataHelper.php
- Okay/Helpers/MetadataHelpers/PostMetadataHelper.php
- Okay/Helpers/MetadataHelpers/ProductMetadataHelper.php
Добавляет приведение к типу "string" в MetadataHelpers во всех случаях, когда мы не можем быть уверены в типе данных.
Строгая типизация и соответствие логике кода.
> Casting to type 'string' in MetadataHelpers

- backend/Helpers/BackendOrdersHelper.php
Убирает жестко прописанные префиксы БД в BackendOrdersHelper
Возникают ошибки когда префикс отличный от дефолтного
> Removed hardcoded db prefix

- Okay/Modules/OkayCMS/NovaposhtaCost/NovaposhtaCost.php
Устанавливает лимит в запросе модуля Новой Почты равному 1000000
До недавнего времени, отсутствие явного указания лимита в запросе означало отсутствие лимита. Теперь же он по-умолчанию равен 500 записям, что ломает логику кода. Чтобы исправить ситуацию, теперь лимит указывается в явном виде.
> Setting NP API request limit to 1000000

- backend/Controllers/ImportAdmin.php
- backend/Controllers/ReportStatsAdmin.php
- backend/Helpers/BackendExportHelper.php
- backend/ajax/export_orders.php
- backend/ajax/export_stat.php
- backend/ajax/export_subscribes.php
- backend/ajax/export_users.php
Меняет порядок кодировки в экспорте и иморте. Меняет использование iconv на mb_convert_encoding.
Изменение порядка вызова кодирования нужно из-за повторного кодированния одной и той же информации, что приводило к ошибкам.
Использование mb_convert_encoding обусловлено его большей предсказуемостью и меньшей зависимостью от системы на которой выполняется код, а точнее от имплементации библиотеки iconv в системе.
> Changed iconv encoding to mb_convert_encoding

- backend/design/html/index.tpl
Исправляет подсчет количества символов в поле meta_title и meta_description при copy-paste в эти поля, при редактировании страниц с телефона
> fix length calculating on mobile when copy-past data

- Okay/Modules/OkayCMS/NovaposhtaCost/Extenders/BackendExtender.php
- Okay/Modules/OkayCMS/NovaposhtaCost/Init/Init.php
Исправлено назначение переменной с id модуля новой почты. Если заказ был новый, то расширение не работало.
Неправильная работа полей новой почты при создании нового зазказ в админке.
> Fixed assigning novaposhta module id

- backend/Helpers/BackendOrderHistoryHelper.php
- backend/design/html/order_history.tpl
В истории заказов в комментарии администратора в верстки удалил очистку от тегов.
При сохранении в историю производится очистка от тегов кроме разрешенных.
Необходимо для возможности сохранения админом красивого форматирования своего комментария.
> Fixed logic escape admin comment for order history

- backend/design/js/filemanager/config/config.php
Была удалена лишняя конфигурационная настройка вызывающая в новой версии php 8 ошибку
На php 8  при использовании плагина filemanager в редакторе TinyMCE происходила ошибка из-за mb_http_input метода
> Fixed error related with mb_http_input in filemanager

- Okay/Core/Entity/filter.php
Исправлена ошибка при использовании метода find если в фильтр у столбца приходило null значение, 
Был некорректный результат срабатывания. А теперь ещё получили возможности искать со значениями NULL
> Fixed bug: error when in filt null data

- 1DB_changes/update_4.3.0.sql
- Okay/Entities/FeaturesEntity.php
- Okay/Helpers/ProductsHelper.php
- backend/Controllers/FeaturesAdmin.php
- backend/Requests/BackendFeaturesRequest.php
- backend/design/html/feature.tpl
- backend/design/html/features.tpl
- backend/lang/en.php
- backend/lang/ru.php
- backend/lang/ua.php
add in sql table "ok_features" column show_in_product and you can on\off show this feature in front product page  
If don`t created colmn use update sql 4.3.0. 
Feature not show in product page some time.
> fix feature show in product page

- Okay/Core/Routes/Strategies/Brand/DefaultStrategy.php
Была доработана логика при пустом значении префикса, добавляется статическая часть в таком случае.
Если не была сохранена настройка префикса (brand_routes_template__default) в БД тогда адрес страницы бренда формировался неправильно (на странице всех брендов и в админке в карточке бренда неправильная ссылка)
> Fixed error in Default strategy in Brand when empty settings

- Okay/Core/Notify.php
Заменено на имя метода для привязки при помощи ExtenderFacade
Теперь возможно корректно перехватывать и модифицировать объект при отправки почты PHPMailer
> Fixing the connection location when smtp sending mail to PHPMailer

- Okay/Core/TemplateConfig/FrontTemplateConfig.php
Пропускает шаг итареции подключения ресурсов (js, css) для модулей которые не активны
Не подключаются лишние ресурсы для не активных модулей
> Fixing logic, no include js and css files module for unactive modules

- design/okay_shop/html/switcher.tpl
Мова та валюта скорочувались у мобільній версії, хоча вони цілком вміщуються, до того ж у десктопній некоректно показувався вибір - і повна і коротка версія разом навіть без пробілу
> Removed tablet lang & currency shortening

- backend/design/html/order.tpl
Некоректно відображувалися стрілки згортання в мобільній версії сторінки заказу
> Fixed mobile arrow icon

- design/okay_shop/html/main.tpl
Двічі використовувався клас нових товарів який не має специфічних стилів, вдруге - на блоці товарів зі знижкою
> Fixed duplicate class name on discount products

- design/okay_shop/js/okay.js
Колір ціни залежав лише від варіанту при відкритті сторінки, бо встановлювався в smarty, тепер при перемиканні варіанту колір теж змінюється відповідно на червоний якщо є знижка і чорний якщо немає
> Added dynamic discount price color change

- backend/design/css/media.css
Стилі що відповідають за нульовий padding справа і зліва робили padding 15px, можливо передбачалося компенсування margin-left -15px але фактично ніде не використовувалося і працювало некоректно
> Remove wrong .pl-0 & .pr-0 override

- design/okay_shop/html/selected_features.tpl
Кнопка "Очистити всі" не показувалась, зокрема, на сторінках "бренди" та "категорії", у шаблоні замість порівняння $route_name було присвоєння $routeName
> Fixed "reset all filters" button

- backend/Requests/BackendFeaturesRequest.php
При сохранении свойства в админ-панели если галочка отключена присваивает значение по умолчанию = 0 
Из-за особенностей checkbox при отключенном элементе checkbox у show_in_product в новое свойство попадало null что приводило в ошибке записи в БД
> Set for feature entity default value = 0 for field show_in_product

- backend/Controllers/ReportStatsAdmin.php
- backend/Helpers/BackendExportHelper.php
- backend/ajax/export_orders.php
- backend/ajax/export_stat.php
- backend/ajax/export_subscribes.php
- backend/ajax/export_users.php
Переконфигурирован метод mb_substitute_character в helper экспорта
Метод используется при экспорте, устарел и вызывал критическую ошибку на PHP выше 8 версии
> Fixed mb_substitute_character function for PHP 8

- composer.json
В файле composer.json немного исправили название библиотеки с symfony/vardumper на symfony/va-rdumper
Некритичная правка на значение указанное в документации
> Fixed config name library var-dumper

- Okay/Core/QueryFactory/Update.php
Аналогично `Update->cols` escape'ит значение для колонки, без `...func_get_args()` второй параметр не передаётся
> Sets one column value placeholder; if an optional second parameter is passed, that value is bound to the placeholder.
> Allow single column placeholder value bind

- Okay/Core/Settings.php
@-оператор заставляет дебаггеры (например Xdebug) в режиме just-in-time (JIT) останавливаться на ошибке, даже если она заглушена, при частом использовании вызывает падение производительности, и служит плохим примером, так как в других случаях не даёт информации об ошибках
> Optionally unserialize without suppressing errors

- Okay/Core/Routes/RouteFactory.php
Добавляет связь к роутеру для all-posts, роут blog
Правка позволяет теперь корректно срабатывать логике добавления в конце адреса слеша если такая настройка активирована
> Fixed slash in end url in all-posts route

- Okay/Modules/OkayCMS/WayForPay/Init/routes.php
Изменен url callback контроллера в модуле WayForPay
Некоторые хостинги не любят заглавные буквы в url, для callback в модуле WayForPay был заменен на все строчные символы
> Fixed callback url in WayForPay module

- Okay/Modules/OkayCMS/Feeds/Core/Presets/Adapters/GoogleMerchantAdapter.php
В Okay\Modules\OkayCMS\Feeds\Core\Presets\Adapters\GoogleMerchantAdapter.php добавил код, который перебирает свойства товара и добавляет их в GoogleMerchant фид как g:product_detail
В "Админке - Товарные фиды - Отдельный фид - Настройки свойств" есть настройки, которые не работают при выбранном шаблоне GoogleMerchant. С этим кодом эти "Настройки свойств" начинают работать.
Проверять так: открывать текст фида и искать "g:product_detail" -- должно быть по несколько штук у товара и содержать данные о свойствах.
Сообщите нам, если это связано с issue(s)/PR(s) (см. https://github.blog/2013-05-14-closing-issues-via-pull-requests/)
> add features to google merchant feed

- backend/design/html/index.tpl
Непосредственные слушатели событий change, keyup, click и т. д. не срабатывали для элементов, добавленных скриптами, например при редактировании названия варианта. Метод .bind() был превзойден методом .on() в версии jQuery 1.7 (2011 год!) и устарел в версии 3.0 (2016). See https://api.jquery.com/on, https://api.jquery.com/bind
> Make direct change listener delegated

- backend/Helpers/BackendFeaturesHelper.php
- backend/design/html/features.tpl
Запрашивались ВСЕ свойства, ВСЕ их значения со всеми колонками, и только для того, чтобы для каждого значения посчитать количество товаров и просуммировать их. Не использовался фильтр свойств, передаваемый в метод (обычно первые 25, на первой странице). Это создавало огромную нагрузку на сервер, так как ВСЕ значения ВСЕХ свойств занимали около 4 Гб оперативки.
> Fix resource-intensive products count query in FeaturesAdmin

- design/okay_shop/html/head.tpl
В og:description прибрав одинарні кавички, поставив подвійні, як це валідно з точки зору HTML.
Також в контент og:description виводимо annotation, а якщо він порожній, тоді виводимо description
Валідний HTML, він більше подобається пошуковикам. Якщо є annotation, краще виводити його, оскільки він більш короткий.
https://github.com/OkayCMS/OkayCMS/issues/276
> fix meta description in OG

- Okay/Core/Router.php
Виправив побудову урла, в якому присутні GET параметри.
На сторінці пошука, при включеному завершаючому слеші для категорій, якщо перейти на категорію, категорія відкривалася по урлу https://demookay.com/catalog/divany?keyword=дивани/ . Тепер урл будується правильно https://demookay.com/catalog/divany/?keyword=дивани
> fix end slash in category on search page

- Okay/Modules/OkayCMS/DeliveryFields/Backend/design/html/order_delivery_fields.tpl
Исправляет ошибки при определенных состояниях в блоке интегрирующимся в админку в карточку заказа
При интеграции в заказ блока из модуля DeliveryFields когда $field->deliveries оказывается пустым то в Smarty метод in_array выдает ошибку если скрипт выполняется на PHP 8.0. Добавлена доппроверка.
> Fixed a bug when the array of shipping methods is empty

- Okay/Core/Router.php
Мелкий фикс редиректа, когда в url присутствует основной язык
Ожидаем попасть из-за понятной(стандартной) логики редиректа с основного языка сайта с префиксом /ua/some-ua-link с 301 редиректом на без префикса /some-ua-link, но попадаем на /some-link со статусом 404, т.к. редирект происходит c удалением всех символов главного языка в url в любом месте
> Fix redirect for main language and remove prefix from url

- Okay/Core/Routes/Strategies/Product/NoPrefixAndCategoryStrategy.php
- Okay/Core/Routes/Strategies/Product/NoPrefixAndPathStrategy.php
- Okay/Core/Routes/Strategies/Product/NoPrefixStrategy.php
- Okay/Core/Routes/Strategies/Product/PrefixAndPathStrategy.php
Проблемы с роутингом товаров в разных стратегиях когда категории и товар содержат только цифры
Исправляет ошибку когда variantId параметр по дефолту перехватывал другие цифровые роуты
> Fixed the issue where the mock variantId parameters were overriding digits URL

- Okay/Controllers/CartController.php
Изменяет/удаляет namespaces в CartController
Исправлено: лишние или неправильные namespaces
> Fix CartController namespace: update FrontTemplateConfig reference, and remove unused imports

- Okay/Modules/OkayCMS/Feeds/Backend/Core/Presets/Adapters/BackendGoogleMerchantAdapter.php
- Okay/Modules/OkayCMS/Feeds/Backend/design/html/presets/google_merchant/settings.tpl
- Okay/Modules/OkayCMS/Feeds/Backend/lang/en.php
- Okay/Modules/OkayCMS/Feeds/Backend/lang/ru.php
- Okay/Modules/OkayCMS/Feeds/Backend/lang/ua.php
- Okay/Modules/OkayCMS/Feeds/Core/Presets/Adapters/GoogleMerchantAdapter.php
- Okay/Modules/OkayCMS/Feeds/Init/module.json
Исправлена ошибка в модуле Feeds / Google Merchant, при которой передавался пустой тег <description> для товаров без описания, добавлены опции заполнения описания.
> Add new options for product description filling in Google Merchant feed
